diabetes-frontend:
  image:
    repository: ghcr.io/baloise-incubator/cc2023_diabetes_angular
    tag: main
    pullPolicy: Always
  network:
    http:
      servicePort: 8080
      ingress:
        host: diabetes-app-test.apps.baloise.dev

diabetes-backend:
  image:
    repository: ghcr.io/baloise-incubator/cc2023_diabetes_springboot
    tag: master
    pullPolicy: Always
  network:
    http:
      servicePort: 8080
      ingress:
        host: diabetes-app-test.apps.baloise.dev
        path: /api
  volumes:
    - name: app-properties
      configMap:
        name: app-properties
  volumeMounts:
    - mountPath: /opt/app/
      name: app-properties
  command:
    - java
    - -jar
    - /app.jar
    - --spring.config.location=/opt/app/application.properties

postgresql-app:
  auth:
    password: "postgres"
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

keycloak: 
  containerSecurityContext: 
    enabled: false
  podSecurityContext:
    enabled: false
  postgresql:
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    auth:
      username: "bn_keycloak"
      password: "password"
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/opt/bitnami/keycloak/data/import//realm.json"
  extraVolumeMounts:
    - name: config
      mountPath: "/opt/bitnami/keycloak/data/import/"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: keycloak-realm
        items:
          - key: "realm.json"
            path: "realm.json"