address-search-index-test:
  image:
    repository: docker.io/library/solr
    tag: latest
  network:
    http:
      servicePort: 8983
      ingress:
        host: address-search-index-test.apps.baloise.dev
