address-search-index-test:
  image:
    repository: docker.io/library/solr
    tag: latest
  network:
    http:
      servicePort: 8983
      ingress:
        host: address-search-index-test.apps.baloise.dev

address-search-client-test:
  image:
    repository: docker.io/gerohoff/address-search-client
    tag: latest
    pullPolicy: Always
  network:
    http:
      servicePort: 8080
      ingress:
        host: address-search-client-test.apps.baloise.dev

address-search-index-bitnami-test:
  image:
    repository: docker.io/bitnami/solr
    tag: latest
  network:
    http:
      servicePort: 8983
      ingress:
        host: address-search-index-bitnami-test.apps.baloise.dev
  env:
    - name: SOLR_CORES
      value: "addresses_core"

