{{- define "monitoring.alertmanager.saAlertmanager" -}}
  {{- $namespace := .namespace -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.alertmanager: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager"}}
  name: alertmanager
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.alertmanager.labels" . | nindent 4 }}
{{ end }}
