{{- define "monitoring.alertmanager.secretAlertmanager" -}}
  {{- $top := .top -}}
  {{- $clusterEnvironment := .clusterEnvironment -}}
  {{- $namespace := .namespace -}}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: alertmanager
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.alertmanager.labels" . | nindent 4 }}
stringData:
  alertmanager.yaml: |
    {{- if $top.Values.alertmanager.customMailTemplate }}
    templates:
    - '/etc/alertmanager/configmaps/notification-template/*.tmpl'
    {{- end }}
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.baloise.dev:25
      smtp_from: devops@baloise.dev
      smtp_require_tls: false
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_match:
          severity: critical
        target_match_re:
          severity: warning|info
      - equal:
          - namespace
          - alertname
        source_match:
          severity: warning
        target_match_re:
          severity: info
      {{- if $top.Values.alertmanager.additionalInhibitRules }}
{{ toYaml $top.Values.alertmanager.additionalInhibitRules | indent 6 }}
      {{- end }}
    receivers:
      - name: default
      {{- if $top.Values.alertmanager.mailAlerts }}
      - name: mail-critical
        email_configs:
        - to: '{{ $top.Values.responsible }}'
          {{- if not $top.Values.alertmanager.customMailTemplate }}
          headers:
            subject: {{ $top.Values.alertmanager.subject | quote }}
          {{- end }}
      {{- end }}
      {{- if $top.Values.alertmanager.webhook.zis }}
      - name: forward2ZIS
        webhook_configs:
        - url: "https://zismain.balgroupit.com/api/webhook/alerts"
          http_config:
            basic_auth:
              username: api-al
              password_file: /etc/alertmanager/secrets/zisapi-secret/password
          send_resolved: true
          max_alerts: 10
      {{- end }}
      {{- if $top.Values.alertmanager.webhook.custom }}
      {{- with index $top.Values.alertmanager.webhook.custom 0 }}
      - name: {{ .name }}
        webhook_configs:
        - url: {{ .url }}
          http_config:
{{ toYaml .httpConfig | indent 12 }}
          send_resolved: true
          max_alerts: 0
      {{- end }}
      {{- end }}
      {{- if $top.Values.alertmanager.teams.prom2teamsEnabled }}
      - name: teams-critical-prod
        webhook_configs:
        - url: "http://localhost:8089/v2/critical"
          send_resolved: true
      - name: teams-warning-prod
        webhook_configs:
        - url: "http://localhost:8089/v2/warning"
          send_resolved: true
      - name: teams-info-prod
        webhook_configs:
        - url: "http://localhost:8089/v2/info"
          send_resolved: true
      - name: teams-critical-nonprod
        webhook_configs:
        - url: "http://localhost:8090/v2/critical"
          send_resolved: true
      - name: teams-warning-nonprod
        webhook_configs:
        - url: "http://localhost:8090/v2/warning"
          send_resolved: true
      - name: teams-info-nonprod
        webhook_configs:
        - url: "http://localhost:8090/v2/info"
          send_resolved: true
      {{- if eq ($top.Values.clusterMonitoringNamespace | toString) ($namespace | toString) }}
      - name: deadmanswitch
        webhook_configs:
        - url: "http://deadmanswitch:8080/ping/bv8e5ooa63m8rt59b780"
          send_resolved: false
      {{- end }}
      {{- end }}
    route:
      group_by:
        - severity
        - env
      group_interval: 5m
      group_wait: 30s
      receiver: default
      repeat_interval: 12h
      routes:
        {{- if $top.Values.alertmanager.webhook.zis }}
        - match_re:
            severity: 'critical|warning'
          receiver: forward2ZIS
          continue: true
        {{- end }}
        {{- if $top.Values.alertmanager.webhook.custom }}
        - match_re:
            severity: 'critical|warning'
          receiver: customwebhook
          continue: true
        {{- end }}
        {{- if $top.Values.alertmanager.mailAlerts }}
        {{- if eq "prod" $clusterEnvironment }}
        - match_re:
            severity: 'critical|warning'
        {{- else }}
        - match:
            severity: critical
        {{- end }}
          receiver: mail-critical
          continue: true
        {{- end }}
        {{- if $top.Values.alertmanager.teams.prom2teamsEnabled }}
        {{- if eq ($top.Values.clusterMonitoringNamespace | toString) ($namespace | toString) }}
        - match_re:
            alertname: DeadMansSwitch
          receiver: 'deadmanswitch'
          group_wait: 0s
          group_interval: 5s
          repeat_interval: 1m
        {{- end }}
        - matchers:
            - env = prod
            - severity = critical
          receiver: teams-critical-prod
        - matchers:
            - env = prod
            - severity = warning
          receiver: teams-warning-prod
        - matchers:
            - env = prod
          receiver: teams-info-prod
        - matchers:
            - env != prod
            - severity= critical
          receiver: teams-critical-nonprod
        - matchers:
            - env != prod
            - severity = warning
          receiver: teams-warning-nonprod
        - matchers:
            - env != prod
            - severity = info
          receiver: teams-info-nonprod
        - matchers:
            - env != prod
          receiver: teams-warning-prod
        {{- end }}
{{ end }}
