apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-crumbs
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
