apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
      - name: webdav
        image: andarius/nginx-upload:1.1.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /tmp/nginx_upload/
          name: datadir
        - mountPath: /var/cache/nginx
          name: dummy
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: pvc-crumbs
      - name: dummy
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: webdav
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webdav
spec:
  host: flux01webdav.baloise.dev
  to:
    kind: Service
    name: webdav
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
