apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
      - name: webdav
        image: drakkan/sftpgo:v2.4.0-alpine-slim
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /srv/sftpgo
          name: datadir
        - mountPath: /var/lib/sftpgo
          name: dummy
        env:
        - name: SFTPGO_WEBDAVD__BINDINGS__0__PORT
          value: "10080"
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: pvc-crumbs
      - name: dummy
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
spec:
  ports:
  - port: 10080
    protocol: TCP
  selector:
    app: webdav
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: web
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webdav
spec:
  host: flux01webdav.apps.okd.baloise.dev
  to:
    kind: Service
    name: webdav
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: web
spec:
  host: flux01web.apps.okd.baloise.dev
  to:
    kind: Service
    name: webdwebav
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
