apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: exit-handlers-
spec:
  entrypoint: intentional-fail
  onExit: exit-handler
  templates:
    - container:
        args:
          - echo intentional failure; exit 1
        command:
          - sh
          - '-c'
        image: 'alpine:latest'
        name: ''
      name: intentional-fail
      name: exit-handler
      steps:
        - - name: notify
            template: send-email
          - name: celebrate
            template: celebrate
            when: '{{`{{workflow.status}}`}} == Succeeded'
          - name: cry
            template: cry
            when: '{{`{{workflow.status}}`}} != Succeeded'
    - container:
        args:
          - >-
            echo send e-mail: {{`{{workflow.name}}`}} {{`{{workflow.status}}`}}
            {{`{{workflow.duration}}`}}. Failed steps {{`{{workflow.failures}}`}}
        command:
          - sh
          - '-c'
        image: 'alpine:latest'
        name: ''
      name: send-email
    - container:
        args:
          - echo hooray!
        command:
          - sh
          - '-c'
        image: 'alpine:latest'
        name: ''
      name: celebrate
    - container:
        args:
          - echo boohoo!
        command:
          - sh
          - '-c'
        image: 'alpine:latest'
        name: ''
      name: cry
