realtime-springboot-client-test:
  image:
    repository: docker.io/lukasbre/realtimecollab-client
    tag: latest
    pullPolicy: Always
  network:
    http:
      servicePort: 8080
      ingress:
        host: realtimecollab-test.apps.baloise.dev
        path: /api
realtime-frontend-test:
  image:
    repository: docker.io/lukasbre/realtimecollab-frontend
    tag: latest
    pullPolicy: Always
  network:
    http:
      servicePort: 8080
      ingress:
        host: realtimecollab-test.apps.baloise.dev
        path: /
