apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: sudoku
  triggers:
    - template:
        name: minio-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: sudoku-
              spec:
                entrypoint: sudoku
                arguments:
                  parameters:
                  - name: path
                    # the value will get overridden by event payload from test-dep
                    value: ""
                templates:
                - name: sudoku
                  inputs:
                    parameters:
                    - name: path
                    artifacts:
                      - name: sudoku-input
                        path: /sudoku/input
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: input
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  outputs:
                    artifacts:
                      - name: sudoku-output
                        path: /tmp/
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: output
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                        archive:
                          none: {}
                  container:
                    image: ghcr.io/luechtdiode/sudoku:0.0.3
                    command: ["/bin/sh", "-c"]
                    args: ["java -cp .:app.jar:libs/* ch.seidel.sudoku.Sudoku /sudoku/{{inputs.parameters.path}} /tmp/"]
          # The container args from the workflow are overridden by the s3 notification key
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: notification.0.s3.object.key
              dest: spec.arguments.parameters.0.value
