apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: sudoku
  triggers:
    - template:
        name: minio-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: sudoku-
              spec:
                entrypoint: whalesay
                templates:
                - name: whalesay
                  inputs:
                    artifacts:
                      - name: sudoku-input
                        path: /sudoku/input/sudoku.txt
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: sudoku.txt
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  outputs:
                    artifacts:
                      - name: sudoku-output
                        path: /sudoku/output/sudoku.txt
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: sudoku-solved.txt
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  container:
                    image: docker/whalesay:latest
                    command: [ "/bin/bash", "-c", "--" ]
                    args: [ "cp /sudoku/input/sudoku.txt /sudoku/output/sudoku.txt && cat /sudoku/output/sudoku.txt" ]
