apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: sudoku
  triggers:
    - template:
        name: minio-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: sudoku-
              spec:
                entrypoint: sudoku
                templates:
                - name: sudoku
                  inputs:
                    artifacts:
                      - name: sudoku-input
                        path: /sudoku/input/
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: input
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  outputs:
                    artifacts:
                      - name: sudoku-output
                        path: /sudoku/output/
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: output
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  container:
                    image: ghrc.io/luechtdiode/sudoku:main
                    command: ["java", "-cp", ".:app.jar", "ch.seidel.sudoku.Sudoku"]