apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: sudoku
  triggers:
    - template:
        name: minio-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: sudoku-
              spec:
                entrypoint: sudoku
                arguments:
                  parameters:
                  - name: path
                    # the value will get overridden by event payload from test-dep
                    value: /sudoku/input/sudoku.txt
                templates:
                - name: sudoku
                  inputs:
                    parameters:
                    - name: path
                    artifacts:
                      - name: sudoku-input
                        path: /sudoku/input
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: input
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  outputs:
                    artifacts:
                      - name: sudoku-output
                        path: /tmp/output
                        s3:
                          endpoint: s3.apps.baloise.dev:443
                          bucket: test
                          key: output
                          accessKeySecret:
                            name: artifacts-minio
                            key: accesskey
                          secretKeySecret:
                            name: artifacts-minio
                            key: secretkey
                  container:
                    image: ghcr.io/luechtdiode/sudoku:0.0.2
                    command: ["/bin/sh", "-c"]
                    args: ["mkdir /tmp/output", "java -cp .:app.jar:libs/* ch.seidel.sudoku.Sudoku {{inputs.parameters.path}}c /tmp/output"]
