minio:
  fullnameOverride: argo-artifacts
  mode: standalone
  persistence:
    size: 2Gi
  resources:
    requests:
      memory: 1Gi
  securityContext:
    enabled: false

  makeUserJob:
    extraVolumes:
      - name: minio-mc
    extraVolumeMounts:
      - mountPath: /etc/minio
        name: minio-mc
  
  buckets:
   # Name of the bucket
    - name: artifacts
      # Policy to be set on the
      # bucket [none|download|upload|public]
      policy: public
      # Purge if bucket exists already
      purge: true
      # set versioning for
      # bucket [true|false]
