minio:
  fullnameOverride: argo-artifacts
  mode: standalone
  persistence:
    size: 2Gi
  resources:
    requests:
      memory: 1Gi
  securityContext:
    enabled: false

  defaultBucket:
    enabled: true
    ## If enabled, must be a string with length > 0
    name: artifacts
    ## Can be one of none|download|upload|public
    policy: public
    ## Purge if bucket exists already
    purge: true