{{- define "monitoring.prometheus.svcThanoSidecar" -}}
  {{- $namespace := .namespace -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: prometheus-0-tls
  labels:
    app.kubernetes.io/component: prometheus-0
    {{- include "monitoring.common.labels" . | nindent 4 }}
  name: prometheus-0
  namespace: {{ $namespace }}
spec:
  ports:
    - name: thanos-sidecar
      port: 10901
      targetPort: grpc
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: prometheus-1-tls
  labels:
    app.kubernetes.io/component: prometheus-0
    {{- include "monitoring.common.labels" . | nindent 4 }}
  name: prometheus-1
  namespace: {{ $namespace }}
spec:
  ports:
    - name: thanos-sidecar
      port: 10901
      targetPort: grpc
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-1
{{ end }}
