apiVersion: v1
kind: Service
metadata:
  labels:
    app: mp-wf-quarkus
    component: postgres
  name: postgres
  namespace: mp-wf-quarkus
spec:
  type: ClusterIP
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: mp-wf-quarkus
    component: postgres