{{- define "monitoring.prometheus.rbPrometheus" -}}
  {{- $namespace := .namespace -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-stack-prometheus-scrapeconfig-reloader
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-cm-reloader
subjects:
  - kind: ServiceAccount
    name: prometheus
{{ end }}
