apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: trigger-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kamelet-tigger
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink