{{- define "monitoring.thanosRuler.secretAlertmanagerConfig" -}}
  {{- $namespace := .namespace -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: thanos-ruler-alertmanager
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.thanosRuler.labels" . | nindent 4 }}
stringData:
  alertmanagers.yml: |
    alertmanagers:
      - api_version: v1
        http_config:
          bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          tls_config:
            insecure_skip_verify: true
        scheme: https
        static_configs:
          - "alertmanager.{{ $namespace }}.svc:9095"
{{ end }}
