{{- define "monitoring.thanosRuler.secretQueryConfig" -}}
  {{- $namespace := .namespace -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: thanos-ruler-query
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.thanosRuler.labels" . | nindent 4 }}
stringData:
  query.yml: |
    - http_config:
        bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        tls_config:
          insecure_skip_verify: true
      scheme: https
      static_configs:
        - "thanos-querier.{{ $namespace }}.svc:9093"
{{ end }}
