apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-k
    camel.apache.org/component: operator
    helm.sh/chart: camel-k-0.7.1
    app.kubernetes.io/name: camel-k
    app.kubernetes.io/instance: baloise-camel-k
    app.kubernetes.io/version: "1.6.1"
    app.kubernetes.io/managed-by: Helm
  name: camel-k-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: camel-k-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: camel-k
        camel.apache.org/component: operator
        name: camel-k-operator
    spec:
      containers:
        - command:
            - kamel
            - operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: camel-k
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/apache/camel-k:1.6.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          name: camel-k-operator
          ports:
            - containerPort: 8080
              name: metrics
          resources: {}
      serviceAccountName: camel-k-operator