gabelstapler-xk6-tempo:
  image:
    repository: ghcr.io/grafana/xk6-client-tracing
    tag: v0.0.2
  env:
    - name: ENDPOINT
      value: "monitoring-stack-tempo-distributor.monitoring-stack.svc:4317"

gabelstapler-xk6-jaeger:
  image:
    repository: ghcr.io/grafana/xk6-client-tracing
    tag: v0.0.2
  env:
    - name: ENDPOINT
      value: http://monitoring-stack-jaeger-collector.monitoring-stack.svc:4317
      # value: "monitoring-stack-opentelemetry-collector.monitoring-stack.svc:4317"

gabelstapler-buggyapp:
  image:
    repository: ghcr.io/baloise-incubator/gabelstapler-buggyapp
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-buggyapp.apps.baloise.dev
  env:
    - name: PYROSCOPE_URL
      value: http://monitoring-stack-pyroscope-distributor.monitoring-stack.svc:4040
    - name: TRACING_URL
      value: http://monitoring-stack-tempo-distributor.monitoring-stack.svc:4317

glutton:
  image:
    repository: docker.io/ubuntu
    tag: lunar
  command: [ "/bin/bash", "-c", "--" ]
  args: [ "while true; do sleep 30; done;" ]
  persistence:
    name: logs
    enabled: true
    accessModes: ReadWriteMany
    size: 5Gi
  volumeMounts:
    - mountPath: /logs
      name: logs

gabelstapler-observability-app-1:
  image:
    repository: ghcr.io/baloise-incubator/gablestapler-observability-app
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-observability-app-1.apps.baloise.dev
  env:
    - name: APP_NAME
      value: gabelstapler-observability-app-1
    - name: USE_CASES_ENDPOINT_1
      value: https://gabelstapler-observability-app-2.apps.baloise.dev
    - name: USE_CASES_ENDPOINT_2
      value: https://gabelstapler-observability-app-3.apps.baloise.dev
    - name: USE_CASES_SCHEDULER_ENDPOINT
      value: https://gabelstapler-observability-app-1.apps.baloise.dev
    - name: TRACING_URL
      value: http://monitoring-stack-tempo-distributor.monitoring-stack.svc:4317
    - name: LOKI_URL
      value: http://monitoring-stack-loki-distributed-distributor.monitoring-stack.svc:3100/loki/api/v1/push

gabelstapler-observability-app-2:
  image:
    repository: ghcr.io/baloise-incubator/gablestapler-observability-app
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-observability-app-2.apps.baloise.dev
  env:
    - name: APP_NAME
      value: gabelstapler-observability-app-2
    - name: TRACING_URL
      value: http://monitoring-stack-tempo-distributor.monitoring-stack.svc:4317
    - name: LOKI_URL
      value: http://monitoring-stack-loki-distributed-distributor.monitoring-stack.svc:3100/loki/api/v1/push

gabelstapler-observability-app-3:
  image:
    repository: ghcr.io/baloise-incubator/gablestapler-observability-app
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-observability-app-3.apps.baloise.dev
  env:
    - name: APP_NAME
      value: gabelstapler-observability-app-3
    - name: USE_CASES_ENDPOINT_1
      value: https://gabelstapler-observability-app-2.apps.baloise.dev
    - name: TRACING_URL
      value: http://monitoring-stack-tempo-distributor.monitoring-stack.svc:4317
    - name: LOKI_URL
      value: http://monitoring-stack-loki-distributed-distributor.monitoring-stack.svc:3100/loki/api/v1/push