gabelstapler:
  image:
    repository: ghcr.io/grafana/xk6-client-tracing
    tag: v0.0.2
  env:
    - name: ENDPOINT
      value: "monitoring-stack-tempo-distributor.monitoring-stack.svc:4317"

gabelstapler-buggyapp:
  image:
    repository: ghcr.io/baloise-incubator/gabelstapler-buggyapp
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-buggyapp.apps.baloise.dev

glutton:
  image:
    repository: docker.io/ubuntu
    tag: lunar