gabelstapler:
  image:
    repository: ghcr.io/grafana/xk6-client-tracing
    tag: v0.0.2
  env:
    - name: ENDPOINT
      value: "monitoring-stack-tempo-distributor.monitoring-stack.svc:4317"

gabelstapler-buggyapp:
  image:
    repository: ghcr.io/baloise-incubator/gabelstapler-buggyapp
    tag: main
    pullPolicy: Always
  network:
    http:
      containerPort: 8080
      ingress:
        host: gabelstapler-buggyapp.apps.baloise.dev
  env:
    - name: PYROSCOPE_URL
      value: http://monitoring-stack-pyroscope-distributor.monitoring-stack.svc:4040
    - name: TRACING_URL
      value: http://monitoring-stack-tempo-distributor.monitoring-stack.svc:4317

glutton:
  image:
    repository: docker.io/ubuntu
    tag: lunar
  command: [ "/bin/bash", "-c", "--" ]
  args: [ "while true; do sleep 30; done;" ]
  persistence:
    enabled: true
    accessModes: ReadWriteMany
    size: 5Gi
    volumeMount: /logs