kind: Secret
apiVersion: v1
metadata:
  name: jaeger
  labels:
    datasource: monitoring-stack
stringData:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: jaeger
        editable: false
        type: jaeger
        url: http://monitoring-stack-jaeger-query.monitoring-stack.svc:80
type: Opaque
