kind: Secret
apiVersion: v1
metadata:
  name: pyroscope
  labels:
    datasource: monitoring-stack
stringData:
  pyroscope.yaml: |
    apiVersion: 1
    datasources:
      - name: pyroscope
        editable: false
        type: grafana-pyroscope-datasource
        url: http://monitoring-stack-pyroscope-querier:4040/
type: Opaque
