{{- define "monitoring.grafana.rbSecretReloader" -}}
  {{- $namespace := .namespace -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-stack-grafana-secret-reloader
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.grafana.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-secret-reloader
subjects:
  - kind: ServiceAccount
    name: grafana
{{ end }}
