# cluster
clusterName: incubator
responsible: codecamp@baloise.dev
routeDomain: apps.baloise.dev
clusterEnvironment: nonprod
appEnvironment: nonprod
infraCluster: true

# monitoring
enableMonitoring: true
enablespringBootMonitoring: true
clusterMonitoringNamespace: platform-monitoring
alertmanager:
  mailAlerts: false
  teams:
    enabled: false
thanosQuerier:
  enableLocalClusterMonitoring: true
  clusterTargets: {}

# Loki
ingress:
  enabled: true
  host: loki-monitoring-stack.apps.baloise.dev
storage: 
  minio:
    enabled: true
monitoring:
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false

tempo-distributed:
  minio:
    enabled: false
  tempo:
    podSecurityContext:
      fsGroup: 1001050000
    securityContext:
      runAsUser: 1001050000
      runAsGroup: 1001050000
