# cluster
clusterName: incubator
responsible: codecamp@baloise.dev
routeDomain: apps.baloise.dev
clusterEnvironment: nonprod
appEnvironment: nonprod
infraCluster: true

# monitoring
enableMonitoring: true
enablespringBootMonitoring: true
clusterMonitoringNamespace: platform-monitoring
alertmanager:
  mailAlerts: false
  teams:
    enabled: false
thanosQuerier:
  enableLocalClusterMonitoring: true
  clusterTargets: {}

# Loki
loki-distributed:
  loki:
    podSecurityContext:
      fsGroup: 1001050000
      runAsGroup: 1001050000
      runAsUser: 1001050000
    containersecurityContext:
      runAsUser: 1001050000
      runAsGroup: 1001050000
  gateway:
    podSecurityContext:
      fsGroup: 1001050000
      runAsGroup: 1001050000
      runAsUser: 1001050000
    containersecurityContext:
      runAsUser: 1001050000
      runAsGroup: 1001050000

# Tempo
tempo-distributed:
  minio:
    enabled: true
    podSecurityContext:
      enabled: false
    securityContext:
      enabled: false
  tempo:
    podSecurityContext:
      fsGroup: 1001050000
    securityContext:
      runAsUser: 1001050000
      runAsGroup: 1001050000
