kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-agent-faro-config
  namespace: monitoring-stack
data:
  agent.yaml: |
    server:
      log_level: 'debug'
    
    metrics:
      wal_directory: '/tmp/agent/wal'
      global: {}
      configs:
        - name: default
          remote_write:
            - url: 'http://prometheus-operated.monitoring-stack.svc:9090/api/v1/write'
    
    logs:
      configs:
        - name: default
          scrape_configs: []
          clients:
            - url: 'http://monitoring-stack-loki-distributed-distributor.monitoring-stack.svc:3100/loki/api/v1/push'
    traces:
      configs:
        - name: 'default'
          remote_write:
            - endpoint: 'monitoring-stack-tempo-distributor.monitoring-stack.svc:4317'
              insecure: true
          receivers:
            otlp:
              protocols:
                grpc: {}
                http:
                  cors:
                    allowed_origins:
                      - http://localhost:5173
                      - https://gabelstapler-frontend-app.apps.baloise.dev
                    max_age: 7200
    
    integrations:
      app_agent_receiver:
        autoscrape:
          enable: true
          metrics_instance: 'default'
        instance: 'frontend'
        logs_instance: 'default'
        traces_instance: 'default'
        server:
          host: '0.0.0.0'
          port: 12345
          api_key: 'secret'
          cors_allowed_origins:
            - http://localhost:5173
            - https://gabelstapler-frontend-app.apps.baloise.dev
        logs_labels: # labels to add to loki log record
          app: frontend # static value
          kind: # value will be taken from log items. exception, log, measurement, etc
        logs_send_timeout: 5000
        sourcemaps:
          download: true
