kind: Secret
apiVersion: v1
metadata:
  name: loki
  labels:
    datasource: monitoring-stack
stringData:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: loki
        access: proxy
        editable: false
        type: loki
        url: http://monitoring-stack-loki-distributed-query-frontend:3100
        version: 1
        uid: loki-1
        jsonData:
          derivedFields:
            - datasourceUid: tempo-1
              matcherRegex: "\StraceId\S:\s\S(\w+)\S"
              name: TraceID
              # url will be interpreted as query for the datasource
              url: '$${__value.raw}'
              # optional for URL Label to set a custom display label for the link.
              urlDisplayLabel: 'View Trace'
type: Opaque
