kind: Secret
apiVersion: v1
metadata:
  name: loki
  labels:
    datasource: monitoring-stack
stringData:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: loki
        access: proxy
        editable: false
        type: loki
        url: http://monitoring-stack-loki-distributed-query-frontend:3100
        version: 1
type: Opaque
