kind: Service
apiVersion: v1
metadata:
  name: grafana-direct
  labels:
    argocd.argoproj.io/instance: monitoring-stack
spec:
  ports:
    - name: grafana-http
      protocol: TCP
      port: 3000
      targetPort: grafana-http
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/part-of: bdop
---
kind: ConfigMap
metadata:
  name: grafana-direct
apiVersion: v1
data:
  nginx.conf: |-
    worker_processes  1;
    
    pid /tmp/nginx.pid;
    
    events {
      worker_connections  1024;
    }
    
    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;
    
      server {
        listen 8080;
    
        location / {
          proxy_set_header  X-Forwarded-User dweber019;
          proxy_set_header  X-Forwarded-Host grafana-direct-nginx;
          proxy_set_header  X-Forwarded-Port 8080;
          proxy_pass        http://grafana-direct:3000;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  grafana-direct
  labels:
    app: grafana-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-direct
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name:  grafana-direct
        app:  grafana-direct
    spec:
      containers:
        - name:  grafana-direct
          image: nginx:1.23-alpine
          ports:
            - name:  http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-conf-volume
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: grafana-direct
          name: nginx-conf-volume
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-direct-nginx
spec:
  ports:
    - name: grafana-direct
      port: 8080
      targetPort: 8080
  selector:
    app: grafana-direct