kind: ConfigMap
apiVersion: v1
metadata:
  name: perses-storage
  namespace: monitoring-stack
data:
  dashboard.json: |
    {
      "kind": "Dashboard",
      "metadata": {
        "name": "prometheus",
        "project": "perses"
      },
      "spec": {
        "datasource": "prometheus",
        "duration": "6h",
        "panels": {
          "foo": {
            "name": "myGraphPanel",
            "kind": "TimeSeriesChart",
            "chart": {
              "lines": [
                {
                  "expr": "up"
                }
              ]
            }
          }
        },
        "layout": {
          "main": {
            "kind": "Expand",
            "parameter": {
              "open": true,
              "children": [
                {
                  "$ref": "#/spec/panels/foo"
                }
              ]
            }
          }
        },
        "entrypoint": {
          "$ref": "#/spec/layouts/main"
        }
      }
    }
  datasource.json: |
    {
      "kind": "Datasource",
      "metadata": {
        "name": "prometheus",
        "project": "perses"
      },
      "spec": {
        "default": true,
        "plugin": {
          "kind": "PrometheusDatasource",
          "spec": {
            "directUrl": "http://thanos-querier-grafana:9090"
          }
        }
      }
    }

