kind: ConfigMap
apiVersion: v1
metadata:
  name: perses-config
  namespace: monitoring-stack
data:
  config.yaml: |
    database:
      file:
        folder: "/perses/storage"
        extension: "json"
    schemas:
      panels_path: "/etc/perses/schemas/panels"
      queries_path: "/etc/perses/schemas/queries"
      datasources_path: "/etc/perses/schemas/datasources"
      variables_path: "/etc/perses/schemas/variables"
      interval: "5m"
