kind: ConfigMap
apiVersion: v1
metadata:
  name: perses-config
  namespace: monitoring-stack
data:
  config.yaml: |
    database:
      file:
        folder: "/perses/storage"
        extension: "json"

