kind: Secret
apiVersion: v1
metadata:
  name: tempo
  labels:
    datasource: monitoring-stack
stringData:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: tempo
        access: proxy
        editable: false
        type: tempo
        url: http://monitoring-stack-tempo-query-frontend:3100
        version: 1
        uid: tempo-1
type: Opaque
