kind: Secret
apiVersion: v1
metadata:
  name: tempo
  labels:
    datasource: monitoring-stack
stringData:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: tempo
        access: proxy
        editable: false
        type: tempo
        url: http://monitoring-stack-tempo-query-frontend:3100
        version: 1
        uid: tempo-1
        jsonData:
          tracesToLogsV2:
            # Field with an internal link pointing to a logs data source in Grafana.
            # datasourceUid value must match the uid value of the logs data source.
            datasourceUid: 'loki-1'
            spanStartTimeShift: '1h'
            spanEndTimeShift: '-1h'
            tags: [{ key: 'service.name', value: 'app' }]
            filterByTraceID: false
            filterBySpanID: false
            customQuery: true
            query: '{$${__tags}} | json | traceId = "$${__span.traceId}"'
          tracesToMetrics:
            datasourceUid: 'thanos-querier-1'
            spanStartTimeShift: '1h'
            spanEndTimeShift: '-1h'
            tags: [{ key: 'service.name', value: 'container' }]
            queries:
              - name: 'Sample query'
                query: 'sum(rate(http_server_requests_seconds_sum{$$__tags}[5m]))'
          serviceMap:
            datasourceUid: 'thanos-querier-1'
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: 'loki-1'
          traceQuery:
            timeShiftEnabled: true
            spanStartTimeShift: '1h'
            spanEndTimeShift: '-1h'
          spanBar:
            type: 'Tag'
            tag: 'http.path'
type: Opaque
