apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent
subjects:
  - kind: ServiceAccount
    name: agent
roleRef:
  kind: Role
  name: kubedock
  apiGroup: rbac.authorization.k8s.io
