kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs
