{{- define "monitoring.networkPolicy" -}}
  {{- $top := .top -}}
  {{- $namespace := .namespace -}}
  {{- $monitoringSelector := .monitoringSelector -}}
  {{- $namespaceConfig := .namespaceConfig -}}
  {{- $enableNamespaceCreation := .enableNamespaceCreation -}}
  {{- $enableNetworkPolicyCreation := .enableNetworkPolicyCreation -}}
  {{- if and ($enableNetworkPolicyCreation) ($enableNamespaceCreation) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-cluster-{{ $top.Values.clusterMonitoringNamespace }}
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ $top.Values.clusterMonitoringNamespace }}
  podSelector: {}
  {{- end }}
{{ end }}
