{{- define "monitoring.pushgateway.networkPolicy" -}}
  {{- $top := .top -}}
  {{- $namespace := .namespace -}}
  {{- $monitoringSelector := .monitoringSelector -}}
  {{- $namespaceConfig := .namespaceConfig -}}
  {{- $enableNamespaceCreation := .enableNamespaceCreation -}}
  {{- $enableNetworkPolicyCreation := .enableNetworkPolicyCreation -}}
  {{- if and ($enableNetworkPolicyCreation) ($enableNamespaceCreation) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access-to-pushgateway
  namespace: {{ $namespace }}
  labels:
    {{- include "monitoring.pushgateway.labels" . | nindent 4 }}
spec:
# Allow push metrics to pushgateway from all namespaces managed by that tenant
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              monitoringselector: {{ $monitoringSelector }}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: pushgateway
  {{- end }}
{{ end }}
